### ISSUE TITLE
pip3 install podcast_downloader installs not-latest version

### ISSUE THREAD

**Issue by BNolet** [dplocki/podcast-downloader#16]
**Describe the bug**
Wrong version of podcast_downloader is installed

**To Reproduce**
1. Run `pip3 install podcast_downloader` or `python3 -m pip install podcast_downloader`
2. Run `pip3 show podcast_downloader`
3. Observe version installed is 0.1.1

**Expected behavior**
Version of install to be 0.2.0 or latest

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Python version: 3.9
 - Version: 0.1.1
 - Link to RSS feed: Not applicable

**Additional context**
Originally thought this was an issue with the app itself, but realized I didn't actually have the latest version of the package

**Comment by dplocki** [comment]
Now, the new version should be available: https://pypi.org/manage/project/podcast-downloader/releases/

**Comment by dplocki** [comment]
Closing :)
