### ISSUE TITLE
Support mp4 file downloads

### ISSUE THREAD

**Issue by jhunschejones** [dplocki/podcast-downloader#19]
**Is your feature request related to a problem? Please describe.**
Some podcasts like [this one](https://anchor.fm/s/26aec4fc/podcast/rss) have both `.mp3` and `.m4a` audio files. 

**Describe the solution you'd like**
It would be cool if the script could download both kinds!

**Describe alternatives you've considered**
Doing it in a [shell command](https://unix.stackexchange.com/questions/495449/command-line-tool-to-download-complete-podcast-from-rss-feed) instead 🤷🏻 😅  I prefer the way your script keeps track of files already downloaded though!

**Comment by dplocki** [comment]
I see, so single item could have `.mp3` xor `.m4a`, for moment I thought there are items with both `.mp3` and `.m4a`. That will make things easier.
