### ISSUE TITLE
Include the episode title in the file name

### ISSUE THREAD

**Issue by blasferna** [dplocki/podcast-downloader#24]
**Is your feature request related to a problem? Please describe.**
For a better organization it would be interesting to include the possibility that the file name contains the episode title

**Describe the solution you'd like**
A new flag in the configuration could be `require_title`

**Comment by Sigvatr** [comment]
Hi, do you have maybe a link to RSS (not obligatory, just it would be nice to examine it), and how the file name should like? Something like: `killing_clown_the_it_review_episode_12.mp3`?

**Comment by dplocki** [comment]
How the name of the file should looks like? Something like this: `it_the_attack_of_killing_clown.mp3"? Do you have maybe also a link to RSS channel for inspection?

**Comment by blasferna** [comment]
This is an RSS that I was testing: https://feeds.megaphone.fm/allearsenglish

According to my preference it is better to keep the source title without underscore, example: `AEE 1905: We Hope You’ll Use this Impressive English Grammar.mp3`

**Comment by dplocki** [comment]
I didn't know, close the merge request close the issue. But anyway:
I have implemented the custom template for file name after downloading. I hope you will find it useful.

**Comment by dplocki** [comment]
I noticed you comment in the merge section, but here I think it will be better to write.

I have been tested the scrip for given feed, seems work fine.
What was the last downloaded file according to the script?

You can find it on logs section (here mine):

```
[2023-01-14 13:24:59] Last downloaded file "AEE 1920  Just Make It Easy! Use One Word to Get to the Core of Things in English.mp3"
```
