### ISSUE TITLE
Can't download from this RSS

### ISSUE THREAD

**Issue by luckybencosmos** [dplocki/podcast-downloader#26]
**Describe the bug**
Can't download from this RSS: "https://www.omnycontent.com/d/playlist/6dd8413b-ede6-483a-bf4e-ab80014939de/20f4bf02-d62f-40b2-b532-af10011ba71b/2bdbf0f4-e0ca-4343-9fb2-af10011ba729/podcast.rss"

**To Reproduce**
jason file:
```
{
    "if_directory_empty": "download_from_4_days",
    "podcasts": [
        {
            "name": " Listening Time",
            "rss_link": "https://www.omnycontent.com/d/playlist/6dd8413b-ede6-483a-bf4e-ab80014939de/20f4bf02-d62f-40b2-b532-af10011ba71b/2bdbf0f4-e0ca-4343-9fb2-af10011ba729/podcast.rss",
            "path": "./ttt",
            "file_name_template": "[%publish_date%] %title%.%file_extension%"
        }
    ]
}
```

Command:
`python3 -m podcast_downloader`

**Expected behavior**
Download episodes.

**Error message**
```
[2023-02-05 14:48:21] Loading configuration (from file: "~/.podcast_downloader_config.json")
[2023-02-05 14:48:21] Checking " Listening Time"
[2023-02-05 14:48:22] Last downloaded file "<none>"
[2023-02-05 14:48:22]  Listening Time: Nothing new
[2023-02-05 14:48:22] ------------------------------
[2023-02-05 14:48:22] Finished
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python version Python 3.8.10
 - Version ??? (I don't know this mean the version of what.) 
 - Link to RSS feed [e.g. https://www.omnycontent.com/d/playlist/6dd8413b-ede6-483a-bf4e-ab80014939de/20f4bf02-d62f-40b2-b532-af10011ba71b/2bdbf0f4-e0ca-4343-9fb2-af10011ba729/podcast.rss]

**Comment by dplocki** [comment]
Hi, according to your configuration, you if have empty directory, you downloading all episodes since 4 days. The last episode from the RSS you provided, has been publish 30 Jan, so 6 days ago.

If you change the value from `download_from_4_days` to `download_from_6_days` (today at least, tomorrow it has be 7 days), it will download the episode from 30 Jan. Eventually use option `download_last`.

**Comment by JorgeQuevedoC** [comment]
Hi, I am trying to download an episode of this feed, but not sure what to use in the `path` configuration value. I haven't been able to run it with the demo in the Readme

`{
  "if_directory_empty": "download_from_4_days",
  "podcasts": [
    {
      "name": "The Skeptic Guide",
      "rss_link": "http://www.theskepticsguide.org/feed/rss.aspx",
      "path": "~/podcasts/SGTTU"
    }
  ]
}
`

![image](https://user-images.githubusercontent.com/19591200/221477148-f373a411-0d50-4bb3-9916-e4a7abc30704.png)

**Comment by dplocki** [comment]
Hi. It is MacOS? Thanks for reporting the issue. Before I the fix, you may enter the whole path instead of `~` (I guessing `/Users/Jorge/podcasts/SGTTU` -> make sure that path exists).

**Comment by JorgeQuevedoC** [comment]
Hi. It did solve it, but now I am getting a different error 
![image](https://user-images.githubusercontent.com/19591200/221645447-63de6fcd-8ca9-4b68-ad30-3fdf5233bd6f.png)

**Comment by dplocki** [comment]
You are using the older code, I have already fix that error: https://github.com/dplocki/podcast-downloader/commit/cc7aa114a14671cc646202e60df63d5e1d8c7274

**Comment by JorgeQuevedoC** [comment]
@dplocki it works beautifully!!

**Comment by dplocki** [comment]
Hi - Just making sure: your problem has been solved?
