### ISSUE TITLE
Please, add new variables.

### ISSUE THREAD

**Issue by Blackspirits** [dplocki/podcast-downloader#31]
Hi, thanks for the excellent work.

**1 - I came to ask if you could add new variables.**

For example in this RSS I would like to get the description and the author
[https://www.omnycontent.com/d/playlist/8c0a4104-a688-4e57-91fd-ad7b00d5dddd/a32cf512-c3ce-4057-8ec8-af3400c547e5/ac708daf-04da-4352-ae6d-af3400ca82ad/podcast.rss](https://www.omnycontent.com/d/playlist/8c0a4104-a688-4e57-91fd-ad7b00d5dddd/a32cf512-c3ce-4057-8ec8-af3400c547e5/ac708daf-04da-4352-ae6d-af3400ca82ad/podcast.rss)

**2 - In the same RSS gives this error**

[←[2m2023-05-08 16:42:55←[0m] ←[31mError:←[0m The podcast file "←[97mhttps://traffic.omny.fm/d/clips/8c0a4104-a688-4e57-91fd-ad7b00d5dddd/a32cf512-c3ce-4057-8ec8-af3400c547e5/f789c11e-447f-460d-a89c-af390172e0b3/audio.mp3?utm_source=Podcast&in_playlist=ac708daf-04da-4352-ae6d-af3400ca82ad←[0m" could not be saved to disk "←[97mC:\Users\Filipe Mota/Downloads/Podcast/A caminho do Catar\[20221027] Portugueses a viver no Catar  "É um país muito rico e compensa vir para cá trabalhar".mp3←[0m" due to the following error:
←[97m[Errno 22] Invalid argument: 'C:\\Users\\Filipe Mota/Downloads/Podcast/A caminho do Catar\\[20221027] Portugueses a viver no Catar  "É um país muito rico e compensa vir para cá trabalhar".mp3'←[0m

**3 - In the RSS below this error in ep1 and in the trailer.**

[←[2m2023-05-08 15:43:26←[0m] ←[31mError:←[0m The podcast file "←[97mhttps://traffic.omny.fm/d/clips/b04d3ae5-22c4-41b6-b20a-aa54000ba759/4093b241-20e0-4025-8a00-afba013b2218/29e80dd4-0527-4d7d-85e9-afc401721117/audio.mp3?utm_source=Podcast&in_playlist=b150e14d-4d2e-4c4e-9cf2-afba013f7a91←[0m" could not be saved to disk "←[97mC:\Users\Filipe Mota/Downloads/Podcast/O Sargento na Cela 7\[20230314] Estreia. "O Sargento na Cela 7". Episódio 1  O Prisioneiro.mp3←[0m" due to the following error:
←[97m[Errno 22] Invalid argument: 'C:\\Users\\Filipe Mota/Downloads/Podcast/O Sargento na Cela 7\\[20230314] Estreia. "O Sargento na Cela 7". Episódio 1  O Prisioneiro.mp3'←[0m

[https://www.omnycontent.com/d/playlist/b04d3ae5-22c4-41b6-b20a-aa54000ba759/4093b241-20e0-4025-8a00-afba013b2218/b150e14d-4d2e-4c4e-9cf2-afba013f7a91/podcast.rss](https://www.omnycontent.com/d/playlist/b04d3ae5-22c4-41b6-b20a-aa54000ba759/4093b241-20e0-4025-8a00-afba013b2218/b150e14d-4d2e-4c4e-9cf2-afba013f7a91/podcast.rss)

**4 - And I wish there was an alternative to the date.**

YEARMMDD and YEAR.MM.DD

With the dots on the dates it would make it a lot easier to read

**5 - I have a question**

The possibility of having more than one podcast in a JSON file? Well, I tried and I couldn't.

**6 - Error because of accents**

[https://rss.podplaystudio.com/3240.xml](https://rss.podplaystudio.com/3240.xml)

![error](https://user-images.githubusercontent.com/11444904/236862183-734fbcd6-ffa5-40a2-9ca8-5857b2305daf.jpg)

Thanks and keep up the great work.
Best regards,
BlackSpirits

**Comment by Blackspirits** [comment]
The idea is not to put it in the file name, for the name I would add the title. The idea was to add the description in the file properties.

![image](https://user-images.githubusercontent.com/11444904/236874770-7cdac52a-5b6e-4c94-ac55-358dcd14eb9e.jpg)

that way you would have a description for each file, that is, a summary of the episode.

And thank you so much again ;)

**Comment by dplocki** [comment]
The script is not supporting setting mp3 tags

**Comment by dplocki** [comment]
The version 1.5.1 should not allow quote character in file name. Regarding the data format, I will work on it.
What is a problem with point 6?

**Comment by Blackspirits** [comment]
if the text of the path has accents, it gives an error

**Comment by dplocki** [comment]
In the version 0.6.1 I have force loading configuration as uft-8, it may solve problem with the problem the directory having accents letters.

**Comment by Blackspirits** [comment]
What about point 4, the possibility of working on it?
thanks

**Comment by dplocki** [comment]
Hi. Yea, I will try do something with that in coming days.
