### ISSUE TITLE
Podcast Downloader cannot download podcast from bowuzhi.fm

### ISSUE THREAD

**Issue by YoungKang1222** [dplocki/podcast-downloader#33]
**Describe the bug**
I tried to use Podcast Downloader to download podcast from [bowuzhi.fm](http://bowuzhi.fm/), but got the following error:
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Desktop (please complete the following information):**
 - [Link to RSS feed](https://bowuzhi.fm/feed/audio.xml)

**Comment by dplocki** [comment]
Hi, apparently the server is require User Agent for the request. I will soon add the proper changes.

**Comment by dplocki** [comment]
Hi, I deploy the version 0.6.0 with support of the HTTP headers
