### ISSUE TITLE
the download result is NONE from this xml https://feed.xyzfm.space/jve6gh9jt8vm

### ISSUE THREAD

**Issue by YoungKang1222** [dplocki/podcast-downloader#36]
**Describe the bug**
the download result is NONE from this xml https://feed.xyzfm.space/jve6gh9jt8vm

**Screenshots**
[?[2m2023-05-27 10:54:22?[0m] Loading configuration (from file: "?[97mD:\AudioProject\data_engineering\podcast-downloader-master\config\config.json?[0m")
[?[2m2023-05-27 10:54:22?[0m] Checking "?[97m北海怪兽?[0m"
[?[2m2023-05-27 10:54:28?[0m] Last downloaded file "?[97m<none>?[0m"
[?[2m2023-05-27 10:54:28?[0m] ?[97m北海怪兽?[0m: Nothing new
[?[2m2023-05-27 10:54:28?[0m] ------------------------------
[?[2m2023-05-27 10:54:28?[0m] Finished

**Comment by YoungKang1222** [comment]
the config is
`{
  "if_directory_empty": "download_all_from_feed",
  "http_headers": {
    "User-Agent": "podcast-downloader"
  },
  "podcasts": [
    {
      "name": "北海怪兽",
      "rss_link": "https://feed.xyzfm.space/jve6gh9jt8vm",
      "path": "D:\\AudioData\\podcasts\\北海怪兽",
      "podcast_extensions": {
        ".m4a": "audio/mp4"
      }
    }
  ],
  "podcast_extensions": {
    ".mp3": "audio/mpeg",
    ".m4a": "audio/x-m4a"
  }
}`

**Comment by dplocki** [comment]
Hi, I have checked your configuration, and seems to work fine.

[2023-05-27 07:38:00] Loading configuration (from file: "~/.podcast_downloader_config.json")
[2023-05-27 07:38:00] Checking "北海怪兽"
[2023-05-27 07:38:05] Last downloaded file "lnd5wuuvfmafo4hidf9slpel6ea6.m4a"
[2023-05-27 07:38:05] 北海怪兽: Nothing new
[2023-05-27 07:38:05] Finished

How your directory

**Comment by YoungKang1222** [comment]
D:\\AudioData\\podcasts\\北海怪兽 is NONE

**Comment by dplocki** [comment]
The directory is empty?
