### ISSUE TITLE
 rss has no attribute 'href'

### ISSUE THREAD

**Issue by YoungKang1222** [dplocki/podcast-downloader#39]
**Describe the bug**
it' s not this project fault but the podcast rss fault, i wonder if there's a solution.
the rss like ' https://feeds.audiomeans.fr/feed/88cf4afb-075f-42e2-b94b-3f3d4ed98f69.xml', download it and it will return: "AttributeError: object has no attribute 'href' "

**To Reproduce**
{"if_directory_empty": "download_all_from_feed",
    "podcasts": [
        {
            "name": "test",
            "rss_link": "https://feeds.audiomeans.fr/feed/88cf4afb-075f-42e2-b94b-3f3d4ed98f69.xml",
            "path": "~/test"
        }
}
![image](https://github.com/dplocki/podcast-downloader/assets/30460985/9f98ac26-a472-4897-8889-23fb49dfc8af)

**Comment by dplocki** [comment]
Hi, sorry, for so late looking at this, I didn't notice the message. The problem is in the script, and it require a patch. Working on it

**Comment by dplocki** [comment]
Done, in version 0.6.2

**Comment by YoungKang1222** [comment]
great job, thanks dplocki!
