### ISSUE TITLE
The downloaded audio does not match the audio provided by rss.      

### ISSUE THREAD

**Issue by YoungKang1222** [dplocki/podcast-downloader#58]
**To Reproduce**
1. Enter configuration
{
    "if_directory_empty": "download_all_from_feed",
    "podcasts": [
        {
            "name": "Thai PBS Podcast",
            "rss_link": "https://www.thaipbspodcast.com/program-rss.php?id=133",
            "path": "xxx",
            "podcast_extensions": {".mp3": "audio/x-m4a"}
        }].
}

2. See error 
The file sizes are all 65KB and there is a read error.     

**Screenshots**
![image](https://github.com/dplocki/podcast-downloader/assets/30460985/7113f84f-c0bd-4a33-b952-6064c51f80cd)

**Comment by dplocki** [comment]
Hi, I have used your configuration and the files seems to be fine (~40 MB each). Maybe it was temporary problem with the hosting server. Try to change the extensions one of the downloaded file and see if those is, for example, a HTML with explanation what is going on (the 65k suggest that, but it is my guess).

If you download lot of files, the server could block you after a while. In that case, you can try set up the limits for downloads and run the script few times, during the week (it should fill up the missing files).

**Comment by YoungKang1222** [comment]
I tried changing the extension to `.html` and it doesn't display correctly, it may be some other type of file; I'll set a download limit later; thanks for the suggestion!

**Comment by YoungKang1222** [comment]
I tried setting `--downloads_limit` to 10, and it still downloads 65KB files; maybe the hosting server set a limit.

**Comment by dplocki** [comment]
Can you download a single file "by hand" (enter the page etc)?
2. If you run the command `head` on the downloaded file, it will looks like this?

```sh
$ head 8dc305f6632a8f1e7ad63385f81b069e.mp3 
ID3L{TYER2021TDAT1808TIME2201PRIVAXMP<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 7.0-c000 79.217bca6, 2021/06/14-18:28:11        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
    xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:bext="http://ns.adobe.com/bwf/bext/1.0/"
```
If yes, it means that you have first 65K of the whole file.

You can also try run this code, it suppose to download one of the files directly in the manner of the script.

```py
url = 'https://audio.thaipbspodcast.com/tracks/133/94371e985bffae501b8668104bb347f5.mp3'
path_to_file = '94371e985bffae501b8668104bb347f5.mp3'

import urllib

link = 'https://audio.thaipbspodcast.com/tracks/133/94371e985bffae501b8668104bb347f5.mp3'
path_to_file = '94371e985bffae501b8668104bb347f5.mp3'

request = urllib.request.Request(link, headers={'User-Agent': 'podcast-downloader'})
with urllib.request.urlopen(request) as response:
    with open(path_to_file, "wb") as file:
        file.write(response.read())
```

**Comment by YoungKang1222** [comment]
* I can download the file manually.
* `head` content shows the likely thing you show.
*  What are the root causes of the problem?

**Comment by dplocki** [comment]
Thanks for the debugging

**Comment by YoungKang1222** [comment]
Great work!
