### ISSUE TITLE
Is there timeout reboot or timeout skip feature？

### ISSUE THREAD

**Issue by YoungKang1222** [dplocki/podcast-downloader#60]
**Is your feature request related to a problem? Please describe.**
When I download many  episodes of a podcast, it probably block for a long time when downloading one episode  and I have to manually kill the program and restart it, which isn't automated enough.

**Describe the solution you'd like**
 I'm wondering if it's possible to set up a timeout restart or skip mechanism to ensure that the podcast list in the config ends up downloading smoothly

**Comment by dplocki** [comment]
Something like following?

```sh
python3 -m podcast_downloader --downloads_limit 10 && sleep 20
python3 -m podcast_downloader --downloads_limit 10 && sleep 20
python3 -m podcast_downloader --downloads_limit 10 && sleep 20
```

**Comment by YoungKang1222** [comment]
yeah, something like this.
*Or another realise:
the `sleep` argument might config for one episode for a podcast like:
`
{
"if_directory_empty": "download_all_from_feed",
"podcasts": [
{
"name": "Thai PBS Podcast",
"sleep": '20'
"rss_link": "https://www.thaipbspodcast.com/program-rss.php?id=133",
"path": "xxx",
"podcast_extensions": {".mp3": "audio/x-m4a"}
}].
}
`
When the current episode is blocked, if it `sleep` times out, start downloading next episode or another way.

**Comment by RolaCoding** [comment]
I have the same problem,often have to reboot at midnight,the problem is as follows:
![image](https://github.com/dplocki/podcast-downloader/assets/30858816/959b7114-a432-4cc2-85f2-dcd0ea70266a)

hope:When the current episode is blocked, if it sleep times out, start downloading next episode or another way.

**Comment by YoungKang1222** [comment]
the lastest code seems normally, but there is a path creating problem:
'''
Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\podcast-downloader-master\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Anaconda3\envs\podcast-downloader-master\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\data\Edge\podcast-downloader-master\podcast-downloader-master2\podcast_downloader\__main__.py", line 251, in <module>
    get_extensions_checker(rss_podcast_extensions), rss_source_path
  File "D:\data\Edge\podcast-downloader-master\podcast-downloader-master2\podcast_downloader\downloaded.py", line 31, in get_downloaded_files
    for file in get_files_from(podcast_directory)
  File "D:\data\Edge\podcast-downloader-master\podcast-downloader-master2\podcast_downloader\downloaded.py", line 21, in get_files_from
    return sorted(os.listdir(directory_path), key=sort_key_function, reverse=True)
FileNotFoundError: [WinError 3] 
'''
