### ISSUE TITLE
Non-existing feed does not cause error

### ISSUE THREAD

**Issue by dplocki** [dplocki/podcast-downloader#61]
**Describe the bug**

Non-existing feed, but script act normally, like nothing happened.

**To Reproduce**
Steps to reproduce the behaviour:
```json
{
    "if_directory_empty": "download_from_4_days",
    "podcasts": [
        {
            "name": "Python for dummies",
            "rss_link": "http://python-for-dummies/atom.rss",
            "path": "~/podcasts/PythonForDummies"
        },
```

Log:

```
[2024-03-21 21:29:59] Checking "Python for dummies"
[2024-03-21 21:29:59] Last downloaded file "<none>"
[2024-03-21 21:29:59] Python for dummies: Nothing new
```

**Expected behavior**
An error?:)

**Comment by YoungKang1222** [comment]
I used the latest code with the same config file as you, but **no files are downloaded** and the **path directory** is not automatically created
![image](https://github.com/dplocki/podcast-downloader/assets/30460985/cb921e7e-b6bf-4641-bd84-703348213122)
